# Generated by Django 2.2.2 on 2021-09-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='本文'),
        ),
    ]
